# Generated by Django 4.1.2 on 2022-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Photo',
            new_name='PhotoFileName',
        ),
    ]
